### ISSUE TITLE
无法删除页面：- (void)pushController:(NSString *)aController storyboard:(NSString *)aStoryboard params:(NSDictionary *)aParams animated:(BOOL)animated removeControllers:(NSArray *)removeControllers;

### ISSUE THREAD

**Issue by grittymindy** [pozi119/VVManager#1]
<pre>
- (void)pushController:(NSString *)aController storyboard:(NSString *)aStoryboard params:(NSDictionary *)aParams animated:(BOOL)animated removeControllers:(NSArray *)removeControllers{
    [self pushController:aController storyboard:aStoryboard params:aParams animated:animated];
    if(removeControllers == nil || self.currentNaviController == nil){
        return;
    }
    NSMutableArray *willRemoveControllers = [NSMutableArray array];
    NSMutableArray *tmpArray = [self.currentNaviController.viewControllers mutableCopy];
    for (NSString *removeController in removeControllers) {
        if (![removeController isEqualToString:aController]) {
            for (UIViewController *viewController in tmpArray) {
                if ([NSStringFromClass([viewController class]) isEqualToString:removeController]) {
                    [willRemoveControllers addObject:viewController];
                }
            }
        }
    }
    [tmpArray removeObjectsInArray:willRemoveControllers];
}
</pre>

VOVCManager中这个方法应该是没办法真正把removeControllers从self.currentNaviController中删除的吧。所操作的tmpArray只是一个mutableCopy.

**Comment by pozi119** [comment]
谢谢!

我晚上仔细检查一下!

最近太忙,暂时也没用这个,你可以自己修改一下.

应该要在此方法的最后一行加上:
