### ISSUE TITLE
App 没有启动的时候, Remote Notification 无法跳转

### ISSUE THREAD

**Issue by dongeyoung** [pozi119/VVManager#4]
App 没有启动的时候, Remote Notification 发送一个跳转请求, 比如 跳转 favoriteDetail 界面. App 收到提醒, 点击进入以后, 还是显示主界面. 我也试过用把App杀了, 用safari从url里面跳转vvm://favoriteDetail, 但是第一次启动的时候, 不能够执行. 只有App从后台或者在前台的时候, 才能够正常跳转, 这个有什么办法解决吗? 谢谢~

**Comment by pozi119** [comment]
使用url的方式跳转, 需要先调用registerURLPath, 只要在AppDelegate调用openURL之前注册即可.
